import { RiskAlert, RegionData, InterventionTracker, ChartDataPoint } from './types';

// All 47 Kenyan Counties with pilot areas
export const regions: RegionData[] = [
  { name: 'Kajiado', score: 74, climate: 72, food: 68, water: 58, livelihood: 76, alerts: 3 },
  { name: 'Makueni', score: 66, climate: 61, food: 64, water: 58, livelihood: 72, alerts: 2 },
  { name: 'Nakuru', score: 59, climate: 55, food: 62, water: 51, livelihood: 68, alerts: 1 },
  { name: 'Samburu', score: 62, climate: 58, food: 61, water: 55, livelihood: 65, alerts: 2 },
  { name: 'Turkana', score: 58, climate: 52, food: 59, water: 48, livelihood: 61, alerts: 3 },
  { name: 'West Pokot', score: 65, climate: 63, food: 66, water: 60, livelihood: 71, alerts: 1 },
  { name: 'Kiambu', score: 76, climate: 74, food: 75, water: 72, livelihood: 78, alerts: 1 },
  { name: 'Mombasa', score: 72, climate: 69, food: 71, water: 68, livelihood: 74, alerts: 1 },
  { name: 'Kwale', score: 68, climate: 65, food: 67, water: 62, livelihood: 70, alerts: 2 },
  { name: 'Kilifi', score: 67, climate: 64, food: 66, water: 61, livelihood: 69, alerts: 2 },
  { name: 'Laamu', score: 61, climate: 58, food: 60, water: 54, livelihood: 64, alerts: 2 },
  { name: 'Garissa', score: 57, climate: 51, food: 58, water: 48, livelihood: 60, alerts: 3 },
  { name: 'Wajir', score: 56, climate: 50, food: 57, water: 46, livelihood: 59, alerts: 3 },
  { name: 'Isiolo', score: 59, climate: 54, food: 60, water: 50, livelihood: 62, alerts: 2 },
  { name: 'Murang\'a', score: 75, climate: 73, food: 74, water: 70, livelihood: 77, alerts: 1 },
  { name: 'Nyeri', score: 77, climate: 75, food: 76, water: 73, livelihood: 79, alerts: 0 },
  { name: 'Kirinyaga', score: 74, climate: 72, food: 73, water: 69, livelihood: 76, alerts: 1 },
  { name: 'Nairobi', score: 78, climate: 76, food: 77, water: 75, livelihood: 80, alerts: 0 },
  { name: 'Embu', score: 71, climate: 69, food: 70, water: 66, livelihood: 73, alerts: 1 },
  { name: 'Tharaka-Nithi', score: 68, climate: 65, food: 67, water: 62, livelihood: 70, alerts: 1 },
  { name: 'Meru', score: 69, climate: 66, food: 68, water: 64, livelihood: 71, alerts: 1 },
  { name: 'Elgeyo-Marakwet', score: 63, climate: 60, food: 62, water: 57, livelihood: 66, alerts: 2 },
  { name: 'Uasin Gishu', score: 70, climate: 68, food: 69, water: 65, livelihood: 72, alerts: 1 },
  { name: 'Kericho', score: 73, climate: 71, food: 72, water: 68, livelihood: 75, alerts: 1 },
  { name: 'Bomet', score: 72, climate: 70, food: 71, water: 67, livelihood: 74, alerts: 1 },
  { name: 'Kisii', score: 74, climate: 72, food: 73, water: 70, livelihood: 76, alerts: 0 },
  { name: 'Nyamira', score: 71, climate: 69, food: 70, water: 66, livelihood: 73, alerts: 1 },
  { name: 'Narok', score: 64, climate: 61, food: 63, water: 58, livelihood: 67, alerts: 2 },
  { name: 'Transmara', score: 62, climate: 59, food: 61, water: 56, livelihood: 65, alerts: 2 },
  { name: 'Siaya', score: 70, climate: 67, food: 69, water: 64, livelihood: 72, alerts: 1 },
  { name: 'Kisumu', score: 69, climate: 66, food: 68, water: 63, livelihood: 71, alerts: 1 },
  { name: 'Homa Bay', score: 67, climate: 64, food: 66, water: 61, livelihood: 69, alerts: 1 },
  { name: 'Migori', score: 65, climate: 62, food: 64, water: 59, livelihood: 67, alerts: 2 },
  { name: 'Kony', score: 68, climate: 65, food: 67, water: 62, livelihood: 70, alerts: 1 },
  { name: 'Busia', score: 66, climate: 63, food: 65, water: 60, livelihood: 68, alerts: 1 },
  { name: 'Kakamega', score: 72, climate: 70, food: 71, water: 67, livelihood: 74, alerts: 1 },
  { name: 'Bungoma', score: 70, climate: 68, food: 69, water: 65, livelihood: 72, alerts: 1 },
  { name: 'Trans-Nzoia', score: 71, climate: 69, food: 70, water: 66, livelihood: 73, alerts: 1 },
  { name: 'Vihiga', score: 73, climate: 71, food: 72, water: 68, livelihood: 75, alerts: 0 },
  { name: 'Mandera', score: 55, climate: 49, food: 56, water: 44, livelihood: 58, alerts: 4 },
  { name: 'Marsabit', score: 54, climate: 48, food: 55, water: 42, livelihood: 57, alerts: 3 },
];

export const alerts: RiskAlert[] = [
  {
    id: '1',
    severity: 'high',
    title: 'Elevated water stress',
    region: 'Kajiado',
    description: 'Water availability indicators show sustained pressure.',
    timestamp: '2 hours ago',
    confidence: 0.92,
  },
  {
    id: '2',
    severity: 'high',
    title: 'Rainfall deficit',
    region: 'Makueni',
    description: 'Seasonal rainfall signal below reference range.',
    timestamp: '4 hours ago',
    confidence: 0.88,
  },
  {
    id: '3',
    severity: 'high',
    title: 'Food price pressure',
    region: 'Nakuru',
    description: 'Selected staple prices show upward pressure.',
    timestamp: '6 hours ago',
    confidence: 0.85,
  },
  {
    id: '4',
    severity: 'medium',
    title: 'Livestock condition pressure',
    region: 'Kajiado',
    description: 'Pasture and water indicators require field verification.',
    timestamp: '8 hours ago',
    confidence: 0.76,
  },
  {
    id: '5',
    severity: 'medium',
    title: 'Vegetation decline',
    region: 'Makueni',
    description: 'Vegetation index below seasonal baseline.',
    timestamp: '12 hours ago',
    confidence: 0.82,
  },
  {
    id: '6',
    severity: 'low',
    title: 'Market access watch',
    region: 'Nakuru',
    description: 'Monitor transport and market-access indicators.',
    timestamp: '1 day ago',
    confidence: 0.71,
  },
];

export const interventions: InterventionTracker[] = [
  {
    id: '1',
    name: 'Water access support',
    region: 'Kajiado',
    progress: 78,
    status: 'on-track',
    target: '100 boreholes',
  },
  {
    id: '2',
    name: 'Climate-smart agriculture',
    region: 'Makueni',
    progress: 64,
    status: 'on-track',
    target: '250 farmers trained',
  },
  {
    id: '3',
    name: 'Food market support',
    region: 'Nakuru',
    progress: 52,
    status: 'at-risk',
    target: '15 markets stabilized',
  },
  {
    id: '4',
    name: 'Community early warning',
    region: 'All areas',
    progress: 88,
    status: 'on-track',
    target: '500 alerts disseminated',
  },
];

export const rainfallData: ChartDataPoint[] = [
  { name: 'Jan', value: 85 },
  { name: 'Feb', value: 78 },
  { name: 'Mar', value: 92 },
  { name: 'Apr', value: 65 },
  { name: 'May', value: 58 },
  { name: 'Jun', value: 42 },
];

export const foodSecurityData: ChartDataPoint[] = [
  { name: 'Kajiado', value: 68 },
  { name: 'Makueni', value: 64 },
  { name: 'Nakuru', value: 62 },
];

export const waterStressData: ChartDataPoint[] = [
  { name: 'Jan', value: 0.35 },
  { name: 'Feb', value: 0.42 },
  { name: 'Mar', value: 0.55 },
  { name: 'Apr', value: 0.68 },
  { name: 'May', value: 0.71 },
  { name: 'Jun', value: 0.78 },
];

export const riskScoreBreakdown = [
  { name: 'Climate', value: 72, percentage: 30 },
  { name: 'Food', value: 61, percentage: 25 },
  { name: 'Water', value: 58, percentage: 20 },
  { name: 'Livelihood', value: 76, percentage: 15 },
  { name: 'Nutrition', value: 55, percentage: 10 },
];
