const kenyaCounties = [
  {
    name: 'Baringo',
    code: 'BRG',
    region: 'Rift Valley',
    latitude: 0.3077,
    longitude: 35.7497,
    resilenceScore: 62,
    climateScore: 60,
    foodScore: 61,
    waterScore: 57,
    livelihoodScore: 65,
  },
  {
    name: 'Bomet',
    code: 'BOM',
    region: 'Rift Valley',
    latitude: -0.7734,
    longitude: 35.3949,
    resilenceScore: 72,
    climateScore: 70,
    foodScore: 71,
    waterScore: 67,
    livelihoodScore: 74,
  },
  {
    name: 'Bungoma',
    code: 'BNG',
    region: 'Western',
    latitude: 0.5629,
    longitude: 34.5682,
    resilenceScore: 70,
    climateScore: 68,
    foodScore: 69,
    waterScore: 65,
    livelihoodScore: 72,
  },
  {
    name: 'Busia',
    code: 'BUS',
    region: 'Western',
    latitude: 0.4837,
    longitude: 34.1151,
    resilenceScore: 66,
    climateScore: 63,
    foodScore: 65,
    waterScore: 60,
    livelihoodScore: 68,
  },
  {
    name: 'Elgeyo-Marakwet',
    code: 'EMA',
    region: 'Rift Valley',
    latitude: 0.8244,
    longitude: 35.4573,
    resilenceScore: 63,
    climateScore: 60,
    foodScore: 62,
    waterScore: 57,
    livelihoodScore: 66,
  },
  {
    name: 'Embu',
    code: 'EMB',
    region: 'Eastern',
    latitude: -0.5014,
    longitude: 37.4509,
    resilenceScore: 71,
    climateScore: 69,
    foodScore: 70,
    waterScore: 66,
    livelihoodScore: 73,
  },
  {
    name: 'Garissa',
    code: 'GRS',
    region: 'North Eastern',
    latitude: -0.4547,
    longitude: 39.6497,
    resilenceScore: 57,
    climateScore: 51,
    foodScore: 58,
    waterScore: 48,
    livelihoodScore: 60,
  },
  {
    name: 'Homa Bay',
    code: 'HOM',
    region: 'Nyanza',
    latitude: -0.5533,
    longitude: 34.4504,
    resilenceScore: 67,
    climateScore: 64,
    foodScore: 66,
    waterScore: 61,
    livelihoodScore: 69,
  },
  {
    name: 'Isiolo',
    code: 'ISL',
    region: 'North Eastern',
    latitude: 0.3516,
    longitude: 37.5833,
    resilenceScore: 59,
    climateScore: 54,
    foodScore: 60,
    waterScore: 50,
    livelihoodScore: 62,
  },
  {
    name: 'Kajiado',
    code: 'KJD',
    region: 'Rift Valley',
    latitude: -1.3031,
    longitude: 36.7194,
    resilenceScore: 74,
    climateScore: 72,
    foodScore: 68,
    waterScore: 58,
    livelihoodScore: 76,
  },
  {
    name: 'Kakamega',
    code: 'KKM',
    region: 'Western',
    latitude: 0.2832,
    longitude: 34.7552,
    resilenceScore: 72,
    climateScore: 70,
    foodScore: 71,
    waterScore: 67,
    livelihoodScore: 74,
  },
  {
    name: 'Kericho',
    code: 'KRC',
    region: 'Rift Valley',
    latitude: -0.3667,
    longitude: 35.2833,
    resilenceScore: 73,
    climateScore: 71,
    foodScore: 72,
    waterScore: 68,
    livelihoodScore: 75,
  },
  {
    name: 'Kiambu',
    code: 'KMB',
    region: 'Central',
    latitude: -1.1707,
    longitude: 36.8315,
    resilenceScore: 76,
    climateScore: 74,
    foodScore: 75,
    waterScore: 72,
    livelihoodScore: 78,
  },
  {
    name: 'Kilifi',
    code: 'KLF',
    region: 'Coast',
    latitude: -3.2869,
    longitude: 39.8469,
    resilenceScore: 67,
    climateScore: 64,
    foodScore: 66,
    waterScore: 61,
    livelihoodScore: 69,
  },
  {
    name: 'Kirinyaga',
    code: 'KRY',
    region: 'Central',
    latitude: -0.5226,
    longitude: 37.2234,
    resilenceScore: 74,
    climateScore: 72,
    foodScore: 73,
    waterScore: 69,
    livelihoodScore: 76,
  },
  {
    name: 'Kisii',
    code: 'KSI',
    region: 'Nyanza',
    latitude: -0.6823,
    longitude: 34.7848,
    resilenceScore: 74,
    climateScore: 72,
    foodScore: 73,
    waterScore: 70,
    livelihoodScore: 76,
  },
  {
    name: 'Kisumu',
    code: 'KSM',
    region: 'Nyanza',
    latitude: -0.1031,
    longitude: 34.7681,
    resilenceScore: 69,
    climateScore: 66,
    foodScore: 68,
    waterScore: 63,
    livelihoodScore: 71,
  },
  {
    name: 'Kitui',
    code: 'KTU',
    region: 'Eastern',
    latitude: -1.2921,
    longitude: 38.2789,
    resilenceScore: 64,
    climateScore: 61,
    foodScore: 63,
    waterScore: 58,
    livelihoodScore: 66,
  },
  {
    name: 'Kwale',
    code: 'KWL',
    region: 'Coast',
    latitude: -4.1591,
    longitude: 39.5042,
    resilenceScore: 68,
    climateScore: 65,
    foodScore: 67,
    waterScore: 62,
    livelihoodScore: 70,
  },
  {
    name: 'Laamu',
    code: 'LAM',
    region: 'Coast',
    latitude: -2.5225,
    longitude: 40.8,
    resilenceScore: 61,
    climateScore: 58,
    foodScore: 60,
    waterScore: 54,
    livelihoodScore: 64,
  },
  {
    name: 'Machakos',
    code: 'MChS',
    region: 'Eastern',
    latitude: -2.2175,
    longitude: 37.2652,
    resilenceScore: 68,
    climateScore: 65,
    foodScore: 67,
    waterScore: 62,
    livelihoodScore: 70,
  },
  {
    name: 'Makueni',
    code: 'MKN',
    region: 'Eastern',
    latitude: -2.7149,
    longitude: 37.7576,
    resilenceScore: 66,
    climateScore: 61,
    foodScore: 64,
    waterScore: 58,
    livelihoodScore: 72,
  },
  {
    name: 'Mandera',
    code: 'MND',
    region: 'North Eastern',
    latitude: 3.6333,
    longitude: 41.8667,
    resilenceScore: 55,
    climateScore: 49,
    foodScore: 56,
    waterScore: 44,
    livelihoodScore: 58,
  },
  {
    name: 'Marsabit',
    code: 'MRS',
    region: 'North Eastern',
    latitude: 2.7449,
    longitude: 37.9833,
    resilenceScore: 54,
    climateScore: 48,
    foodScore: 55,
    waterScore: 42,
    livelihoodScore: 57,
  },
  {
    name: 'Meru',
    code: 'MRU',
    region: 'Eastern',
    latitude: 0.0536,
    longitude: 37.6528,
    resilenceScore: 69,
    climateScore: 66,
    foodScore: 68,
    waterScore: 64,
    livelihoodScore: 71,
  },
  {
    name: 'Migori',
    code: 'MGR',
    region: 'Nyanza',
    latitude: -1.0588,
    longitude: 34.4725,
    resilenceScore: 65,
    climateScore: 62,
    foodScore: 64,
    waterScore: 59,
    livelihoodScore: 67,
  },
  {
    name: 'Mombasa',
    code: 'MBA',
    region: 'Coast',
    latitude: -4.0435,
    longitude: 39.6682,
    resilenceScore: 72,
    climateScore: 69,
    foodScore: 71,
    waterScore: 68,
    livelihoodScore: 74,
  },
  {
    name: 'Murang\'a',
    code: 'MRG',
    region: 'Central',
    latitude: -0.6762,
    longitude: 37.1629,
    resilenceScore: 75,
    climateScore: 73,
    foodScore: 74,
    waterScore: 70,
    livelihoodScore: 77,
  },
  {
    name: 'Nakuru',
    code: 'NKR',
    region: 'Rift Valley',
    latitude: -0.2833,
    longitude: 36.0667,
    resilenceScore: 59,
    climateScore: 55,
    foodScore: 62,
    waterScore: 51,
    livelihoodScore: 68,
  },
  {
    name: 'Nairobi',
    code: 'NRB',
    region: 'Central',
    latitude: -1.2864,
    longitude: 36.8172,
    resilenceScore: 78,
    climateScore: 76,
    foodScore: 77,
    waterScore: 75,
    livelihoodScore: 80,
  },
  {
    name: 'Narok',
    code: 'NRK',
    region: 'Rift Valley',
    latitude: -1.1126,
    longitude: 35.4328,
    resilenceScore: 64,
    climateScore: 61,
    foodScore: 63,
    waterScore: 58,
    livelihoodScore: 67,
  },
  {
    name: 'Nyandarua',
    code: 'NYD',
    region: 'Central',
    latitude: -0.5278,
    longitude: 36.3875,
    resilenceScore: 73,
    climateScore: 71,
    foodScore: 72,
    waterScore: 68,
    livelihoodScore: 75,
  },
  {
    name: 'Nyeri',
    code: 'NYR',
    region: 'Central',
    latitude: -0.4167,
    longitude: 36.95,
    resilenceScore: 77,
    climateScore: 75,
    foodScore: 76,
    waterScore: 73,
    livelihoodScore: 79,
  },
  {
    name: 'Samburu',
    code: 'SMB',
    region: 'North Eastern',
    latitude: 1.1167,
    longitude: 37.1833,
    resilenceScore: 62,
    climateScore: 58,
    foodScore: 61,
    waterScore: 55,
    livelihoodScore: 65,
  },
  {
    name: 'Siaya',
    code: 'SYA',
    region: 'Nyanza',
    latitude: 0.0842,
    longitude: 34.2798,
    resilenceScore: 70,
    climateScore: 67,
    foodScore: 69,
    waterScore: 64,
    livelihoodScore: 72,
  },
  {
    name: 'Taita-Taveta',
    code: 'TTV',
    region: 'Coast',
    latitude: -3.4899,
    longitude: 38.2469,
    resilenceScore: 63,
    climateScore: 60,
    foodScore: 62,
    waterScore: 57,
    livelihoodScore: 65,
  },
  {
    name: 'Tharaka-Nithi',
    code: 'TNT',
    region: 'Eastern',
    latitude: 0.1022,
    longitude: 37.7856,
    resilenceScore: 68,
    climateScore: 65,
    foodScore: 67,
    waterScore: 62,
    livelihoodScore: 70,
  },
  {
    name: 'Trans-Nzoia',
    code: 'TRN',
    region: 'Western',
    latitude: 0.8667,
    longitude: 34.85,
    resilenceScore: 71,
    climateScore: 69,
    foodScore: 70,
    waterScore: 66,
    livelihoodScore: 73,
  },
  {
    name: 'Turkana',
    code: 'TRK',
    region: 'North Eastern',
    latitude: 2.3667,
    longitude: 35.9,
    resilenceScore: 58,
    climateScore: 52,
    foodScore: 59,
    waterScore: 48,
    livelihoodScore: 61,
  },
  {
    name: 'Uasin Gishu',
    code: 'UGS',
    region: 'Rift Valley',
    latitude: 0.94,
    longitude: 35.3,
    resilenceScore: 70,
    climateScore: 68,
    foodScore: 69,
    waterScore: 65,
    livelihoodScore: 72,
  },
  {
    name: 'Vihiga',
    code: 'VHG',
    region: 'Western',
    latitude: 0.1022,
    longitude: 34.7537,
    resilenceScore: 73,
    climateScore: 71,
    foodScore: 72,
    waterScore: 68,
    livelihoodScore: 75,
  },
  {
    name: 'Wajir',
    code: 'WJR',
    region: 'North Eastern',
    latitude: 1.7333,
    longitude: 40.0667,
    resilenceScore: 56,
    climateScore: 50,
    foodScore: 57,
    waterScore: 46,
    livelihoodScore: 59,
  },
  {
    name: 'West Pokot',
    code: 'WPK',
    region: 'Rift Valley',
    latitude: 1.4,
    longitude: 35.3,
    resilenceScore: 65,
    climateScore: 63,
    foodScore: 66,
    waterScore: 60,
    livelihoodScore: 71,
  },
];

module.exports = kenyaCounties;
